# Generated by Django 4.1.5 on 2023-01-21 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 20, 40, 58, 982034, tzinfo=datetime.timezone.utc)),
        ),
    ]
